#!/bin/bash

#				LOAD - GPU_ID - N_FEAT - REWARD METHOD GAMMA - MODEL_TRAIN - USE_Q - NORMALIZE_Q - LAYERS - USE_NORMALIZE  - NODE_RANK - N_ATOM 	VMIN - 	VMAX -	DISCOUNT_REWARD - USE_EXP - DIFUSION_WEIGHT - COUNT_WEIGHT - DEGREE_WEIGHT - 2FLOW	USE_LSTM - LAMBDA
python3 main.py 1		0		 2			8	  0		 0.90		0			0		 0			2			0				0			11		 0.0	1.0			0				1			1					0				0			0		0		0	

